---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/ShakedAviv50313/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-RHTAPWATCH-238-progressing-Argocd-apps
